---
title: "LACatLAL_shots"
output: html_document
---

```{r}
source("../RajivFunctions.R")
library(dplyr)
library(tidyr)

library(grid)
library(jpeg)
source("../fullcourt.R")
source("../halfcourt.R")

library(ggplot2)
```

Load in data
```{r}
lac_lal_movements <- sportvu_convert_json("LACatLAL.json")
plays <- read.csv("LACatLAL_playbyplay.csv")
```

```{r}
shots <- read.csv("shot_df.csv")
lakers_shots <- shots[1:77, ]
clippers_shots <- shots[78:nrow(shots),]

```

Combine movements and plays data 
```{r}
fulltrack <- merge(lac_lal_movements, plays, by.x = "event.id",
      by.y = "EVENTNUM", keep = TRUE)
```

Combine play calls/results into one column
```{r}
fulltrack <- fulltrack %>%
  unite("Play", c(HOMEDESCRIPTION, VISITORDESCRIPTION), na.rm = TRUE, remove = FALSE)
```


```{r}
unique(fulltrack$SCORE)

fulltrack <- separate(fulltrack, col = "SCORE", into = c("Clippers", "Lakers"), sep = "-")
fulltrack$Clippers <- as.numeric(fulltrack$Clippers)
fulltrack$Lakers <- as.numeric(fulltrack$Lakers)
```

Fill in score for all non-scoring plays

```{r}
fulltrack <- fulltrack %>% 
  fill(Lakers) %>%
  fill(Clippers)

unique(fulltrack$Lakers)
```

Fill in data for first NA rows (before the first score is documented, so the score must be 0-0)

```{r}
sum(is.na(fulltrack$Lakers))
sum(is.na(fulltrack$Clippers))

fulltrack[0:42350, ]$Lakers = 0
fulltrack[0:42350, ]$Clippers = 0
unique(fulltrack$Lakers)

head(fulltrack)
```

Fix margin column
```{r}
fulltrack$SCOREMARGIN = 
  fulltrack$Clippers - fulltrack$Lakers
```



```{r}
playbyplay_shots <- 
  filter(fulltrack, EVENTMSGTYPE %in% c(1,2))
playbyplay_shots



lakers_shots_ids <- 
  unique(filter(playbyplay_shots,
                PLAYER1_TEAM_NICKNAME =="Lakers")
         $event.id)

lakers_tracking_shots <- filter(playbyplay_shots, 
                       event.id %in% lakers_shots_ids)

lakers_shots[duplicated(lakers_shots$description), ]


lakers_shots[lakers_shots$description == "Jordan Clarkson  misses 25-foot three point jumper", ]











clippers_shots_ids <- 
  unique(filter(playbyplay_shots,
                PLAYER1_TEAM_NICKNAME =="Clippers")
         $event.id)

clippers_tracking_shots <- filter(playbyplay_shots, 
                       event.id %in% clippers_shots_ids)


merge(x = clippers_tracking_shots, y = clippers_shots,
      by.x = "Play", by.y = "description")
```





