---
title: "LACatLAL_Analysis"
output: html_document
---

```{r}
source("../RajivFunctions.R")
library(dplyr)
library(tidyr)

library(grid)
library(jpeg)
source("../fullcourt.R")
source("../halfcourt.R")

library(ggplot2)
```

Load in data
```{r}
lac_lal_movements <- sportvu_convert_json("../LACatLAL.json")
str(lac_lal_movements)
plays <- read.csv("LACatLAL_playbyplay.csv")
str(plays)
```

Combine movements and plays data 
```{r}
fulltrack <- merge(lac_lal_movements, plays, by.x = "event.id",
      by.y = "EVENTNUM", keep = TRUE)
```

Combine play calls/results into one column
```{r}
fulltrack <- fulltrack %>%
  unite("Play", c(HOMEDESCRIPTION, VISITORDESCRIPTION), na.rm = TRUE, remove = FALSE)
```


```{r}
unique(fulltrack$SCORE)

fulltrack <- separate(fulltrack, col = "SCORE", into = c("Clippers", "Lakers"), sep = "-")
fulltrack$Clippers <- as.numeric(fulltrack$Clippers)
fulltrack$Lakers <- as.numeric(fulltrack$Lakers)
```

Fill in score for all non-scoring plays

```{r}
fulltrack <- fulltrack %>% 
  fill(Lakers) %>%
  fill(Clippers)

unique(fulltrack$Lakers)
```

Fill in data for first NA rows (before the first score is documented, so the score must be 0-0)

```{r}
sum(is.na(fulltrack$Lakers))
sum(is.na(fulltrack$Clippers))

fulltrack[0:42350, ]$Lakers = 0
fulltrack[0:42350, ]$Clippers = 0
unique(fulltrack$Lakers)

head(fulltrack)
```

Fix margin column

```{r}
fulltrack$SCOREMARGIN = fulltrack$Clippers - fulltrack$Lakers

ggplot(fulltrack, aes(SCOREMARGIN)) +
  geom_histogram(bins = 8)
```

```{r}
ball_movements = fulltrack[fulltrack$lastname == "ball", ]
ball_movements
```

```{r}
first_play = fulltrack[fulltrack$event.id == 2, ]

first_play_shot = first_play[(first_play$lastname == "Bryant" |
                                first_play$lastname == "ball"), ]

fullcourt() + 
  geom_point(data = first_play_shot, 
       aes(x_loc, y_loc, alpha = game_clock, color = lastname)) +
  ggtitle("First Play of the Game: Kobe Miss")
```



```{r}
make <- fulltrack[which(fulltrack$EVENTMSGTYPE == 1),]

first_basket = fulltrack[fulltrack$event.id == 6, ]

first_basket_shot = first_basket[(first_basket$lastname == "Griffin" |first_basket$lastname == "ball"), ]

fullcourt() + 
  geom_point(data = first_basket_shot, 
       aes(x_loc, y_loc, alpha = game_clock, color = lastname)) +
  ggtitle("First Score of the Game: Blake G. Layup")

range(first_basket$game_clock)
```



```{r}
balltime <- first_basket %>% 
  group_by(event.id) %>% 
  filter(lastname=="ball")  %>% 
  #62 feet is the within 28 feet for the right side of the court
  summarise(clock28 = max(game_clock[x_loc>50])) %>% 
  print(event.id,clock28)

dfall <- first_basket %>% 
  filter(game_clock == balltime$clock28) %>% 
  filter(lastname!="ball") %>% 
  select(team_id,x_loc,y_loc)

colnames(dfall) <- c('ID','X','Y')
head(dfall)
```

```{r}
df_hull2 <- dfall %>% filter(ID == min(ID)) %>% select(X,Y)
c.hull2 <- chull(df_hull2)  #Calculates convex hull#
c.hull3 <- c(c.hull2, c.hull2[1]) #You need five points to draw four line segments, so we add the first set of points at the end
df2 <- as.data.frame(cbind(1,df_hull2[c.hull3 ,]$X,df_hull2[c.hull3 ,]$Y))
colnames(df2) <- c('ID','X','Y')
df2 # The points of the convex hull

ggplot(df2, aes(x=X, y=Y)) + geom_polygon()  

```

```{r}
chull.coords <- df_hull2[c.hull3 ,]
library(sp)
chull.poly <- Polygon(chull.coords, hole=F)  #From the package sp
chull.area <- chull.poly@area
chull.area

dfcentroid <- c(mean(df_hull2[c.hull2 ,]$X),mean(df_hull2[c.hull2 ,]$Y))
dfcentroid 
```




```{r}
##These functions assume you have all the movement data in a data frame called total

#Convert data into suitable format
total <- first_basket
total$x_loc_r <- total$x_loc
total$y_loc_r <- total$y_loc

#Get data for building graphic
# total <- total %>% 
#   filter(game_clock == 671.03, event.id == 6)
# total
# 
# total %>% 
#     filter(game_clock == gameclock, event.id == eventid)


dplayer <- player_position(6, 684.35) #Gets positions of players
dchull <- chull_plot(6,684.35	)       #Gets area of convex hull
dcentroid <- chull_plot_centroid(6,684.35)  #Gets centroid of convex hull

```

```{r}
#Plot graphic
fullcourt() + 
    ##Add players
    geom_point(data=dplayer,
               aes(x=X,y=Y,group=ID, label = Name),
               color=dense_rank(dplayer$ID),
               size=5) +
  geom_text(data = dplayer, 
            aes(label=Name, x = X, y = Y + 3)) + 
  scale_colour_brewer() +
    ##Add Convex hull areas
  geom_polygon(data=dchull,aes(x=X,y=Y,group=ID),
               fill=dense_rank(dchull$ID),
               alpha = 0.2) + 
  scale_fill_brewer() + 
    ##Add Centroids
  scale_shape_identity() +
  geom_point(data=dcentroid,aes(x=X,y=Y,group=dcentroid$ID),
             color=(dcentroid$ID),
             size=3, shape=8) 
```


```{r}
##These functions assume you have all the movement data in a data frame called total

#Convert data into suitable format
total <- first_basket
total$x_loc_r <- total$x_loc
total$y_loc_r <- total$y_loc

#Get data for building graphic
# total <- total %>% 
#   filter(game_clock == 671.03, event.id == 6)
# total
# 
# total %>% 
#     filter(game_clock == gameclock, event.id == eventid)


dplayer <- player_position(6, 666.10) #Gets positions of players
dchull <- chull_plot(6,666.10)       #Gets area of convex hull
dcentroid <- chull_plot_centroid(6,666.10)  #Gets centroid of convex hull

```

```{r}
#Plot graphic
fullcourt() + 
    ##Add players
    geom_point(data=dplayer,
               aes(x=X,y=Y,group=ID, label = Name),
               color=dense_rank(dplayer$ID),
               size=5) +
  geom_text(data = dplayer, 
            aes(label=Name, x = X, y = Y + 3)) + 
  scale_colour_brewer() +
    ##Add Convex hull areas
  geom_polygon(data=dchull,aes(x=X,y=Y,group=ID),
               fill=dense_rank(dchull$ID),
               alpha = 0.2) + 
  scale_fill_brewer() + 
    ##Add Centroids
  scale_shape_identity() +
  geom_point(data=dcentroid,aes(x=X,y=Y,group=dcentroid$ID),
             color=(dcentroid$ID),
             size=3, shape=8) 
```
